name: botkube

on:
  push:
    paths:
      - '.github/workflows/botkube.yml'
      - 'build/botkube/**'
      - '!build/botkube/*.md'

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          BASE_DIR=build/botkube
          VERSION=$(cat ${BASE_DIR}/.version)
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=base_dir::${BASE_DIR}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2.4.0
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            raspbernetes/botkube:${{ github.sha }}
            ghcr.io/raspbernetes/botkube:${{ github.sha }}

      - name: Build and Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.4.0
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            raspbernetes/botkube:latest
            raspbernetes/botkube:${{ steps.prep.outputs.version }}
            ghcr.io/raspbernetes/botkube:latest
            ghcr.io/raspbernetes/botkube:${{ steps.prep.outputs.version }}
