name: prometheus-operator-config-reloader

on:
  push:
    paths:
      - '.github/workflows/prometheus-operator-config-reloader.yml'
      - 'build/prometheus-operator-config-reloader/**'
      - '!build/prometheus-operator-config-reloader/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/prometheus-operator-config-reloader/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare
        id: prep
        run: |
          BASE_DIR=build/dex
          VERSION=$(cat ${BASE_DIR}/.version)
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=base_dir::${BASE_DIR}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/prometheus-operator-config-reloader:${{ github.sha }} \
            --file ./build/prometheus-operator-config-reloader/Dockerfile \
            ./build/prometheus-operator-config-reloader/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/prometheus-operator-config-reloader:latest \
            --tag raspbernetes/prometheus-operator-config-reloader:${{ env.VERSION }} \
            --tag k8sathome/prometheus-operator-config-reloader:${{ env.VERSION }} \
            --file ./build/prometheus-operator-config-reloader/Dockerfile \
            ./build/prometheus-operator-config-reloader/ \
            --output "type=image,push=true"
